# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  pythonVersion: 3.8

pool:
  name: my-agent-pool

steps:
  - bash: pip install azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
    displayName: 'Install and Upgrade Azure CLI'
