# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  pythonVersion: 3.8

pool:
  name: my-agent-pool

steps:
  - script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Install and Upgrade Azure CLI'
  
  - task: AzureCLI@2
    displayName: 'Upload app to azure'
    inputs:
      azureSubscription: 'Avanade Delivery(3eba6e29-3983-495b-a539-c3c4b43fb90c)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az webapp up -n lakshmi --os-type Linux --resource-group lakshmichakka  --location eastus2 --runtime "python|3.6"'
      workingDirectory: 'src/'
