# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  pythonVersion: 3.8

pool:
  name: my-agent-pool

jobs:
- job: deploy
  steps:
  - script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Install and Upgrade Azure CLI'
  
  - task: AzureCLI@2
    displayName: 'Deploy app to azure'
    inputs:
      azureSubscription: '$(Azure_Subscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az webapp up -n $(APP_NAME) --os-type Linux --resource-group $(RG_NAME)  --location $(LOCATION) --runtime "python|3.6"'
      workingDirectory: 'src/'

  - task: AzureCLI@2
    displayName: 'connection string'
    inputs:
      azureSubscription: '$(Azure_Subscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az webapp config appsettings set -g $(RG_NAME) -n $(APP_NAME) --settings DATABASE_URI=mysql://lakshmi@lakshmi-app-server:Password123@lakshmi-app-server.mysql.database.azure.com:3306/serverDB'